repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.4
    hooks:
      - id: clang-format
        args: [--style=Google]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cpplint
